"""Regenerate every derived figure the documents publish.

A number in a document is either captured output or a claim somebody typed. The command
output in the README is the first kind already. The tables are derived, and until this
existed each one was regenerated by whatever was to hand on the day it was written, which
is a figure whose provenance is a memory.

    python scripts/figures.py

Prints each block under the document it belongs to. The blocks are byte identical to what
the documents carry, so a document and this script cannot drift without one of them
failing the comparison.
"""
import os
import statistics
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sjp import eventlog, layout, memory, model, plan, skew  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURES = os.path.join(ROOT, "tests", "fixtures", "eventlogs")
JOBS = ("skewed", "balanced", "join")
GROUPING_STAGE = 2
RANGE_METRICS = ("records_read", "duration", "executor_run_time")


def log_for(job):
    directory = os.path.join(FIXTURES, job)
    names = [n for n in sorted(os.listdir(directory)) if not n.endswith(".md")]
    if len(names) != 1:
        raise SystemExit("{} holds {} logs".format(job, len(names)))
    return os.path.join(directory, names[0])


def apps():
    return {job: eventlog.profile(log_for(job)) for job in JOBS}


def reachable_spread(tasks):
    """The largest spread a stage of `tasks` tasks can reach, searched over small values.

    The point is that below three tasks the answer is a property of the task count rather
    than of the data, so the search is over the shape and not over the fixture.
    """
    best, argument = 0.0, None
    limit = 8
    for values in _combinations(tasks, limit):
        middle = statistics.median(values)
        if middle == 0:
            continue
        ratio = max(values) / middle
        if ratio > best:
            best, argument = ratio, values
    return best, argument


def _combinations(tasks, limit):
    if tasks == 0:
        yield ()
        return
    for head in range(1, limit + 1):
        for rest in _combinations(tasks - 1, limit):
            yield (head,) + rest


def threshold_blocks(loaded):
    print("adr-0003")
    for tasks in (1, 2, 3):
        best, argument = reachable_spread(tasks)
        print("n={}  best={:.4f}  at {}".format(tasks, best, argument))
    for tasks in (1, 2, 3):
        values = [1] * (tasks - 1) + [10 ** 6]
        middle = statistics.median(values)
        print("n={}   values [1]*{} + [1e6] -> spread {:.4f}".format(
            tasks, tasks - 1, max(values) / middle))

    stage = loaded["skewed"].stage(GROUPING_STAGE)
    for name in ("memory_spilled", "disk_spilled", "gc_time"):
        values = sorted(stage.values(name))
        print("{:<16} sorted={}  median={}  max={}  {} of {} tasks non zero".format(
            name, values, statistics.median(values), max(values),
            sum(1 for value in values if value), len(values)))

    healthy, guilty = [], []
    for job in ("skewed", "balanced"):
        for stage in loaded[job].stages:
            for name in RANGE_METRICS:
                ratio = stage.spread(name)
                if ratio is None or len(stage.tasks) < skew.MIN_TASKS:
                    continue
                row = "{:.4f} {} stage {} {}".format(ratio, job, stage.stage_id, name)
                (guilty if ratio > 10 else healthy).append((ratio, row))
    healthy.sort(reverse=True)
    guilty.sort()
    print("largest healthy: {}".format([row for _r, row in healthy[:3]]))
    print("smallest guilty: {}".format([row for _r, row in guilty[:3]]))
    print("default threshold {} sits between {} and {}".format(
        skew.DEFAULT_THRESHOLD, healthy[0][1].split()[0], guilty[0][1].split()[0]))


def floor_blocks(loaded):
    print("adr-0003 floor")
    values = set()
    for job in ("skewed", "balanced"):
        for stage in loaded[job].stages:
            for name in model.QUANTITIES:
                if model.kind_of(name) != model.MILLIS:
                    continue
                verdict = skew.judge(stage, name, floors={model.MILLIS: None,
                                                          model.BYTES: None,
                                                          model.COUNT: None})
                if verdict.outcome == skew.SKEWED:
                    values.add(verdict.largest)
    ordered = sorted(values)
    print("millisecond values that produce a skewed verdict with no floor: {}".format(ordered))
    below = max(v for v in ordered if v < skew.FLOORS[model.MILLIS])
    above = min(v for v in ordered if v > skew.FLOORS[model.MILLIS])
    print("the floor of {} sits in the gap between {} and {}".format(
        skew.FLOORS[model.MILLIS], below, above))
    sweep = {}
    # The last sweep point is one above the second largest value, so it is the floor
    # that keeps exactly the biggest millisecond skew and drops everything else.
    for floor in (0, 30, 50, 100, ordered[-2] + 1):
        verdicts = skew.scan(loaded["skewed"], floors={model.MILLIS: floor,
                                                       model.BYTES: None,
                                                       model.COUNT: None})
        sweep[floor] = skew.counts(verdicts)[skew.SKEWED]
    print("skewed verdicts on the skewed log by floor: {}".format(sweep))


def spill_blocks(loaded):
    print("adr-0004")
    skewed = loaded["skewed"]
    grouping = skewed.stage(GROUPING_STAGE)
    first = skewed.stage(0)
    balanced_grouping = loaded["balanced"].stage(GROUPING_STAGE)
    spilled = [value for value in grouping.values("peak_memory") if value]
    quiet = [value for value in grouping.values("peak_memory")
             if value and value < max(grouping.values("peak_memory"))]
    rows = [
        ("memory spilled on the grouping stage", grouping.total(memory.MEMORY)),
        ("disk spilled on the same stage", grouping.total(memory.DISK)),
        ("the sum a total would have published",
         grouping.total(memory.MEMORY) + grouping.total(memory.DISK)),
        ("inflation on stage 0 of both logs", "{:.4f}".format(memory.inflation(first))),
        ("inflation on the grouping stage", "{:.4f}".format(memory.inflation(grouping))),
        ("how far apart those two factors are",
         "{:.2f}".format(memory.inflation(grouping) / memory.inflation(first))),
        ("stage 0 spills this and peaks at zero",
         "{} bytes".format(first.total(memory.MEMORY))),
        ("balanced grouping stage peak, no spill", balanced_grouping.peak_memory),
        ("largest skewed task peak that did not spill", max(quiet)),
        ("the task that did spill peaked at", max(spilled)),
    ]
    for label, value in rows:
        # Padded to a column and then separated, so a label longer than the column still
        # has a space after it. Hand adjusting one row of a table is how a block stops
        # being output and starts being something that looks like output.
        print("{} {}".format(label.ljust(41), value))


def _shuffles(app):
    return layout.shuffles(app, plan.read(app.plans[0]))


def size_blocks(loaded):
    print("adr-0005 sizes")
    rows = []
    for job in JOBS:
        for shuffle in _shuffles(loaded[job]):
            rows.append((job, shuffle))
    for job, shuffle in rows:
        if shuffle.scheme != "hashpartitioning":
            continue
        print("{:<10}{:<24}{:>10} estimated {:>11} measured".format(
            job, shuffle.scheme, shuffle.estimated, shuffle.written))
    common = [s for _job, s in rows if s.scheme == "RoundRobinPartitioning"]
    print("{:<10}{:<24}{:>10} estimated {:>11} measured".format(
        "all three", common[0].scheme, common[0].estimated, common[0].written))

    print("adr-0005 per row")
    seen = []
    for _job, shuffle in rows:
        source_rows = 199 if shuffle.estimated < 100000 else 8000000
        width = shuffle.estimated // source_rows
        if (shuffle.estimated, source_rows) in seen:
            continue
        seen.append((shuffle.estimated, source_rows))
        print("{:>9} / {:>7} = {} bytes a row".format(
            shuffle.estimated, source_rows, width))

    print("adr-0005 origins")
    for job in JOBS:
        print("{:<10}{}".format(job, "  ".join(
            shuffle.origin for shuffle in _shuffles(loaded[job]))))

    print("adr-0005 written")
    for job in ("skewed", "balanced"):
        big = [s for s in _shuffles(loaded[job]) if s.scheme == "hashpartitioning"][0]
        print("{:<10}{}  {} bytes written".format(job, big.scheme, big.written))

    print("adr-0005 join")
    found = layout.candidates(loaded["join"], plan.read(loaded["join"].plans[0]))
    small = [c for c in found if c.worth_it][0]
    print("small side   {} estimated, against a {} threshold".format(
        small.estimated, small.threshold))
    print("large side   {} measured bytes shuffled to meet it".format(small.saved))


def main():
    loaded = apps()
    threshold_blocks(loaded)
    floor_blocks(loaded)
    spill_blocks(loaded)
    size_blocks(loaded)
    return 0


if __name__ == "__main__":
    sys.exit(main())
